'use client';
import Link from 'next/link';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Check,Download,FlaskConical,Layers3,LoaderCircle,Plus,Save,Search,ShieldCheck,Sparkles,Trash2,X} from 'lucide-react';
import {initialStrategy,registry,StrategySchema,formatValue,formatCondition,availableReports} from '../lib/strategy/schema';
import type {Strategy,Condition,Indicator,Snapshot,StockResult,Status} from '../lib/strategy/schema';
import {screen,conflicts,compareStrategies,conditionImpact,missingSnapshotFields} from '../lib/strategy/engine';
import {mockSnapshot} from '../lib/finance/mock';
type Connection={aiConfigured:boolean;dataConfigured:boolean;model:string};
type Saved={id:string;savedAt:string;strategy:Strategy};
const labels:Record<Status,string>={pass:'符合条件',fail:'未满足',unknown:'待核验'};
const examples=['沪深300里，经营改善、估值合理、走势相对稳定的公司','沪深300中净利润同比大于10%，PE低于25倍','把市盈率上限放宽到35倍，其他条件不变'];
const same=(a:unknown,b:unknown)=>JSON.stringify(a)===JSON.stringify(b);
const time=(s:string|null|undefined)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'接口未提供';
function reportLabel(s:string){const [y,q]=s.split('-');return `${y}年${({'1':'一季报','2':'中报','3':'三季报','4':'年报'} as Record<string,string>)[q]}`;}
async function api<T>(url:string,body?:unknown,signal?:AbortSignal):Promise<T>{const res=await fetch(url,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal});const value=await res.json() as T&{error?:string};if(!res.ok)throw new Error(value.error??'请求未完成');return value as T;}
function download(value:unknown){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='aime-strategy.json';a.click();URL.revokeObjectURL(url);}
function Pill({status}:{status:Status}){return <span className={`pill ${status}`}><i/>{labels[status]}</span>;}
export default function Home(){
 const [strategy,setStrategy]=useState<Strategy>(initialStrategy),[query,setQuery]=useState(examples[0]);
 const [connection,setConnection]=useState<Connection|null>(null),[mode,setMode]=useState<'real'|'mock'>('real'),[operation,setOperation]=useState<'create'|'revise'>('create');
 const [draft,setDraft]=useState<Strategy|null>(null),[aiInfo,setAiInfo]=useState(''),[aiBusy,setAiBusy]=useState(false);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[baseline,setBaseline]=useState<Strategy|null>(null),[confirmed,setConfirmed]=useState<Strategy|null>(null);
 const [running,setRunning]=useState(false),[progress,setProgress]=useState({done:0,total:0});
 const [error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'all'|Status>('pass'),[search,setSearch]=useState('');
 const [selected,setSelected]=useState<string|null>(null),[saved,setSaved]=useState<Saved[]>([]),[showSaved,setShowSaved]=useState(false);
 const abort=useRef<AbortController|null>(null),generation=useRef(0);
 useEffect(()=>{let alive=true;api<Connection>('/api/status').then(v=>{if(alive)setConnection(v);}).catch(()=>{if(alive)setError('连接状态暂时无法读取，请刷新重试。');});const restore=setTimeout(()=>{try{const data=JSON.parse(localStorage.getItem('aime-strategies-v1')??'[]');if(Array.isArray(data)&&alive)setSaved(data.filter(x=>typeof x?.id==='string'&&StrategySchema.safeParse(x.strategy).success).slice(0,20));}catch{}},0);return ()=>{alive=false;clearTimeout(restore);abort.current?.abort();};},[]);
 const reports=useMemo(()=>availableReports(),[]),reportAvailable=reports.includes(strategy.report);
 const validation=useMemo(()=>{const s=StrategySchema.safeParse(strategy);const errors=s.success?[...conflicts(strategy),...strategy.unresolved]:s.error.issues.map(x=>x.message);return reportAvailable?errors:[...errors,'当前策略报告期不在可选范围，请重新选择可用报告期。'];},[strategy,reportAvailable]);
 const missingFields=snapshot?missingSnapshotFields(strategy,snapshot):[],needsFields=missingFields.length>0;
 const resultStrategy=needsFields&&confirmed?confirmed:strategy;
 const evaluation=useMemo(()=>{if(!snapshot||validation.length)return {rows:[] as StockResult[],error:''};try{return {rows:screen(resultStrategy,snapshot),error:''};}catch(e){return {rows:[] as StockResult[],error:e instanceof Error?e.message:'无法核验'};}},[resultStrategy,snapshot,validation]);
 const rows=evaluation.rows,counts={pass:rows.filter(x=>x.status==='pass').length,fail:rows.filter(x=>x.status==='fail').length,unknown:rows.filter(x=>x.status==='unknown').length};
 const impact=useMemo(()=>{if(!snapshot||!rows.length||needsFields)return [];try{return conditionImpact(strategy,snapshot);}catch{return [];}},[strategy,snapshot,rows,needsFields]);
 const comparison=useMemo(()=>{if(!baseline||!snapshot||!rows.length||needsFields||same(baseline,strategy))return null;try{return compareStrategies(baseline,strategy,snapshot);}catch{return null;}},[baseline,strategy,snapshot,rows,needsFields]);
 const visible=rows.filter(r=>(tab==='all'||r.status===tab)&&(!search||`${r.code} ${r.name}`.includes(search))).sort((a,b)=>a.code.localeCompare(b.code));
 const detail=rows.find(x=>x.code===selected),changed=snapshot&&!same(strategy,confirmed);
 useEffect(()=>{if(!detail&&!showSaved)return;const focused=document.activeElement as HTMLElement|null,previous=document.body.style.overflow;document.body.style.overflow='hidden';return ()=>{document.body.style.overflow=previous;focused?.focus();};},[detail,showSaved]);
 function update(patch:Partial<Strategy>){setStrategy(s=>({...s,...patch}));setError('');setNotice('');}
 function edit(id:string,patch:Partial<Condition>){setStrategy(s=>({...s,conditions:s.conditions.map(c=>c.id===id?{...c,...patch,assumption:false}:c)}));setError('');}
 function switchMode(next:'real'|'mock'){abort.current?.abort();generation.current++;setRunning(false);setMode(next);setSnapshot(null);setBaseline(null);setConfirmed(null);setSelected(null);setError('');if(next==='mock')update({universe:'sample'});}
 function quickReal(){switchMode('real');update({universe:'sample'});setDraft(null);setOperation('create');setQuery('12只研究样本中，经营改善、估值合理、走势相对稳定的公司');setNotice('已选择12只真实研究样本，非完整市场。请解析并核对草案，确认后获取真实数据；现有编辑条件保留。');}
 async function parseIntent(){if(!query.trim()||aiBusy||running)return;setAiBusy(true);setError('');setNotice('');try{const r=await api<{strategy:Strategy;model:string;attempts:number;requestId:string}>('/api/intent',{query,operation,strategy});setDraft(r.strategy);setAiInfo(`${r.model} · ${r.attempts===1?'一次结构校验通过':'修复后结构校验通过'} · ${r.requestId.slice(0,8)}`);}catch(e){setError(e instanceof Error?e.message:'AI解析失败');}finally{setAiBusy(false);}}
 async function execute(refresh=false){
  if(validation.length||running)return;
  if(snapshot&&!evaluation.error&&!needsFields&&!refresh){setConfirmed(structuredClone(strategy));setNotice('已确认当前条件；结果来自同一份数据快照。');return;}
  const current=structuredClone(strategy),token=++generation.current;abort.current?.abort();const controller=new AbortController();abort.current=controller;setRunning(true);setError('');setNotice('');setProgress({done:0,total:0});
  try{let next:Snapshot;
   if(mode==='mock')next=mockSnapshot(current.report,'sample');
   else{const pool=await api<{stocks:{code:string;name:string}[];timestamp:string|null;requestId:string|null}>(`/api/universe?kind=${current.universe}`,undefined,controller.signal);setProgress({done:0,total:pool.stocks.length});const collected:Snapshot['stocks']=[],fields=[...new Set(current.conditions.map(c=>c.field))];
    for(let i=0;i<pool.stocks.length;i+=12){const batch=pool.stocks.slice(i,i+12),r=await api<{stocks:Snapshot['stocks']}>('/api/data',{codes:batch.map(s=>s.code),fields,report:current.report},controller.signal);if(!Array.isArray(r.stocks)||r.stocks.length!==batch.length||new Set(r.stocks.map(s=>s.code)).size!==batch.length||r.stocks.some(s=>!batch.some(b=>b.code===s.code)))throw new Error('返回股票与请求池不一致，停止生成结果。');collected.push(...r.stocks.map(s=>({...s,name:batch.find(b=>b.code===s.code)?.name??s.name})));if(token!==generation.current)return;setProgress({done:collected.length,total:pool.stocks.length});}
    next={id:crypto.randomUUID(),mode:'real',createdAt:new Date().toISOString(),universe:current.universe==='csi300'?'沪深300':'12只研究样本',universeCount:pool.stocks.length,stocks:collected,report:current.report,warnings:['财务指标为所选报告期，接口未提供公告日，不用于历史时点回测。','估值时间是上游元数据时点，各指标未必完全同步。'],universeEvidence:{observedAt:pool.timestamp,requestId:pool.requestId}};
   }
   if(token!==generation.current)return;setSnapshot(next);setBaseline(current);setConfirmed(current);setTab('pass');setSelected(null);setNotice(mode==='mock'?'已完成构造数据演示；以下不代表真实金融事实。':'已完成全池获取与确定性筛选；请检查证据及缺失状态。');
  }catch(e){if(token!==generation.current)return;setError(controller.signal.aborted?'已停止本次获取。已有快照保留，本次部分数据不生成最终结果。':e instanceof Error?e.message:'数据获取失败');}finally{if(token===generation.current)setRunning(false);}
 }
 function save(){if(!StrategySchema.safeParse(strategy).success||validation.length){setError('请先修正条件与未澄清诉求，再保存策略。');return;}const next=[{id:crypto.randomUUID(),savedAt:new Date().toISOString(),strategy:structuredClone(strategy)},...saved].slice(0,20);try{localStorage.setItem('aime-strategies-v1',JSON.stringify(next));setSaved(next);setNotice('策略已保存在此浏览器，可重开并重新获取数据执行。');}catch{setError('浏览器存储不可用，可下载策略文件。');}}
 function removeSaved(id:string){const next=saved.filter(x=>x.id!==id);try{localStorage.setItem('aime-strategies-v1',JSON.stringify(next));setSaved(next);}catch{setError('浏览器存储不可用。');}}
 return <div className="app-shell">
  <header className="topbar" inert={!!detail||showSaved}><Link className="brand" href="/"><span className="brand-icon"><Layers3 size={22}/></span><span>AIME <b>策略研究台</b><small>自然语言智能选股与策略解释器</small></span></Link><div className="top-actions"><span className="edition">校招笔试 · 可操作原型</span><button className="quiet" onClick={()=>setShowSaved(true)}><Save size={16}/>我的策略 <span className="counter">{saved.length}</span></button><a className="quiet repo" href="https://github.com/1orange-bot/aime-strategy-copilot" target="_blank" rel="noreferrer">源码</a></div></header>
  <main inert={!!detail||showSaved}><div className="page-heading"><div><p className="eyebrow">RESEARCH WORKSPACE</p><h1>让筛选条件，有据可查。</h1><p className="lead">用自然语言表达研究想法，确认条件后再筛选。每个结果都能回到数据与判断依据。</p></div><div className="mode-control" aria-label="数据模式"><button className={mode==='real'?'active':''} onClick={()=>switchMode('real')}>真实数据</button><button className={mode==='mock'?'active':''} onClick={()=>switchMode('mock')}><FlaskConical size={15}/>构造演示</button></div></div>
   <div className={`connection-strip ${mode==='mock'?'demo-strip':''}`}><div><span className={`signal ${connection?.aiConfigured?'on':''}`}/>AI {connection===null?'检查中':connection.aiConfigured?'已配置，待请求验证':'待配置'}<span className="divider"/><span className={`signal ${connection?.dataConfigured?'on':''}`}/>扶摇数据 {connection===null?'检查中':connection.dataConfigured?'已配置，待请求验证':'待配置'}</div><span>{mode==='mock'?'构造测试数据 · 与实际市场无关':'数据按请求获取 · 不承诺实时行情'}</span></div>
   <div className="quick-real-path"><button className="primary" disabled={running||aiBusy} onClick={quickReal}><Search size={16}/>快速真实体验</button><span>12只真实研究样本 · 非完整市场 · 使用真实扶摇数据<br/>完整沪深300仍可在研究股票池中选择。</span></div>
   <section className="intent-panel"><div className="section-title"><span className="step">01</span><h2>表达研究意图</h2><span className="subtle">AI生成草案，执行由你确认</span></div><div className="intent-operation"><button className={operation==='create'?'active':''} onClick={()=>setOperation('create')}>新建策略</button><button className={operation==='revise'?'active':''} onClick={()=>setOperation('revise')}>修改当前策略</button><span>新建仅采用本次诉求；修改保留其余条件。</span></div><label className="sr-only" htmlFor="research-query">研究需求或局部修改</label><textarea id="research-query" value={query} onChange={e=>setQuery(e.target.value)} maxLength={2000} rows={2}/><div className="intent-bottom"><div className="example-list">{examples.map((e,i)=><button key={e} onClick={()=>{setQuery(e);setOperation(i===2?'revise':'create');}} disabled={aiBusy}>{['模糊需求','精确条件','局部修改'][i]} </button>)}</div><button className="primary" disabled={aiBusy||running||!query.trim()} onClick={parseIntent}>{aiBusy?<LoaderCircle className="spin" size={17}/>:<Sparkles size={17}/>} {aiBusy?'正在理解…':'解析为策略草案'}</button></div></section>
   {draft&&<section className="draft-panel"><div className="section-title"><Sparkles size={18}/><h2>待确认的 AI 草案</h2><button className="icon-button" aria-label="放弃AI草案" onClick={()=>setDraft(null)}><X size={18}/></button></div><p className="subtle">{aiInfo}。以下只是条件草案，尚未执行。</p><ul>{draft.conditions.map(c=><li key={c.id}><strong>{registry[c.field].name} {formatCondition(c)}</strong><span>{c.concept}{c.assumption?' · AI提出的默认假设':''}</span></li>)}</ul>{draft.assumptions.map((s,i)=><p className="draft-assumption" key={i}>假设：{s}</p>)}{draft.unresolved.map((s,i)=><p className="unresolved" key={i}>需澄清：{s}</p>)}<p className="subtle">{draft.universe==='csi300'?'沪深300':'12只研究样本'} · {reportLabel(draft.report)}</p><div className="button-row"><button className="primary" disabled={running||mode==='mock'&&draft.universe!=='sample'} onClick={()=>{update(draft);setDraft(null);setNotice('草案已放入编辑区。请核对后确认执行。');}}><Check size={16}/>采用草案并核对</button><button className="quiet" onClick={()=>setDraft(null)}>放弃草案</button>{mode==='mock'&&draft.universe!=='sample'&&<span className="subtle">沪深300草案需先切换真实数据模式。</span>}</div></section>}
   {error&&<div className="alert error" role="alert"><strong>本次未完成</strong><span>{error}</span><button className="icon-button" onClick={()=>setError('')} aria-label="关闭错误"><X size={16}/></button></div>}{notice&&<div className="alert notice" role="status"><Check size={16}/><span>{notice}</span></div>}
   <div className="workspace-grid"><section className="conditions-panel"><div className="section-title"><span className="step">02</span><h2>核对与调整条件</h2><span className="and">全部满足 · AND</span></div><label className="field-label" htmlFor="strategy-name">策略名称</label><input id="strategy-name" value={strategy.name} maxLength={60} disabled={running} onChange={e=>update({name:e.target.value})}/><div className="two-fields"><div><label className="field-label" htmlFor="pool">研究股票池</label><select id="pool" value={strategy.universe} disabled={running||mode==='mock'} onChange={e=>update({universe:e.target.value as Strategy['universe']})}><option value="csi300">沪深300 · 当前成分</option><option value="sample">12只研究样本 · 非完整市场</option></select></div><div><label className="field-label" htmlFor="report">可用财务报告期</label><select id="report" value={reportAvailable?strategy.report:""} disabled={running} onChange={e=>update({report:e.target.value})}>{!reportAvailable&&<option value="" disabled>请选择可用报告期</option>}{reports.map(s=><option key={s} value={s}>{reportLabel(s)}</option>)}</select></div></div>
    <div className="condition-list">{strategy.conditions.map((c,i)=>{const field=registry[c.field],m=impact.find(x=>x.id===c.id),factor=field.percent?100:1;return <div className="condition-card" key={c.id}><div className="condition-top"><span className="condition-number">{String(i+1).padStart(2,'0')}</span><span className="condition-concept">{c.concept}</span>{c.assumption&&<span className="assumption-tag">默认假设</span>}<button className="icon-button delete" aria-label={`删除第${i+1}个条件`} disabled={running||strategy.conditions.length===1} onClick={()=>update({conditions:strategy.conditions.filter(x=>x.id!==c.id)})}><Trash2 size={14}/></button></div><label className="sr-only" htmlFor={`metric-${c.id}`}>第{i+1}个指标</label><select id={`metric-${c.id}`} disabled={running} value={c.field} onChange={e=>{const f=e.target.value as Indicator;edit(c.id,{field:f,concept:registry[f].name,value:c.operator==='between'?[0,registry[f].percent?0.2:30]:registry[f].percent?0.1:30});}}>{(Object.keys(registry) as Indicator[]).map(f=><option value={f} key={f}>{registry[f].name}</option>)}</select><div className="threshold-row"><label className="sr-only" htmlFor={`op-${c.id}`}>第{i+1}个运算符</label><select id={`op-${c.id}`} value={c.operator} disabled={running} onChange={e=>{const operator=e.target.value as Condition['operator'];edit(c.id,{operator,value:operator==='between'?[0,Array.isArray(c.value)?c.value[1]:c.value]:Array.isArray(c.value)?c.value[1]:c.value});}}>{['>','>=','<','<=','=','between'].map(op=><option key={op} value={op}>{op==='between'?'闭区间':op}</option>)}</select>{(Array.isArray(c.value)?c.value:[c.value]).map((v,j)=><div className="number-unit" key={j}><label className="sr-only" htmlFor={`value-${c.id}-${j}`}>第{i+1}个条件{Array.isArray(c.value)?j===0?'下限':'上限':'阈值'}（{field.unit}）</label><input type="number" id={`value-${c.id}-${j}`} value={Number.isFinite(v)?Number((v*factor).toFixed(6)):''} step="any" disabled={running} onChange={e=>{const num=e.target.value===''?NaN:Number(e.target.value)/factor;edit(c.id,{value:Array.isArray(c.value)?c.value.map((old,k)=>j===k?num:old) as [number,number]:num});}}/><span>{field.unit}</span></div>)}</div><p className="metric-hint">{field.hint}</p>{m&&<div className="condition-impact"><span>独立未满足 <b>{m.failed}</b></span><span>待核验 <b>{m.unknown}</b></span><span>移除此条件新增 <b>{m.addedIfRemoved??'—'}</b></span></div>}</div>;})}</div>
    <button className="add-condition" disabled={running||strategy.conditions.length>=10} onClick={()=>update({conditions:[...strategy.conditions,{id:crypto.randomUUID(),concept:'营业收入增长',field:'revenue_yoy',operator:'>',value:0,assumption:true}]})}><Plus size={15}/>增加条件</button>
    {validation.length>0&&<div className="validation" role="alert">{validation.map((s,i)=><p key={i}>{s}</p>)}{strategy.unresolved.length>0&&<p>请补充需求重新解析，或明确放弃不支持的诉求。</p>}{strategy.unresolved.map((s,i)=><button className="quiet" key={i} onClick={()=>update({unresolved:strategy.unresolved.filter((_,j)=>i!==j),assumptions:[...strategy.assumptions.slice(-9),`用户明确本轮放弃：${s}`]})}>本轮不采用：{s}</button>)}</div>}
    <div className="execute-area"><button className="primary execute" disabled={running||aiBusy||validation.length>0||mode==='real'&&!connection?.dataConfigured} onClick={()=>execute()}>{running?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>} {running?'正在获取与核验…':needsFields?'重新获取并执行':snapshot&&!evaluation.error?'确认当前条件':'确认并执行筛选'}</button>{running?<><progress max={progress.total||1} value={progress.done}/><p className="subtle" role="status">{progress.total?`已核验 ${progress.done} / ${progress.total} 只，全池完成后展示结果。`:'正在读取股票池…'}</p><button className="quiet" onClick={()=>abort.current?.abort()}>停止获取</button></>:<p className="subtle">{mode==='mock'?'使用12只构造公司，不产生实际选股结论。':!connection?.dataConfigured?'接口待配置；可调整策略或切换构造演示。':'含逐股票财务和行情请求，获取全池可能需数分钟。'}</p>}<div className="button-row"><button className="quiet" onClick={save} disabled={running}><Save size={14}/>保存策略</button><button className="quiet" onClick={()=>download(strategy)} disabled={validation.length>0}><Download size={14}/>下载条件</button></div></div>
   </section><section className="results-panel"><div className="section-title"><span className="step">03</span><h2>查看结果与证据</h2>{snapshot&&<button className="quiet refresh" disabled={running||validation.length>0||mode==='real'&&!connection?.dataConfigured} onClick={()=>execute(true)}>重新获取数据</button>}</div>
    {!snapshot?<div className="empty-state"><div className="empty-art"><Search size={32}/><span/><span/></div><h3>先确认你要研究的条件</h3><p>结果将展示符合条件、未满足和待核验股票，<br/>保留每项指标的原始值、来源和时间。</p><div className="empty-flow"><span>研究意图</span><span>可编辑条件</span><span>证据结果</span></div><button className="quiet" onClick={()=>{switchMode('mock');setNotice('已切换构造演示。确认并执行，可体验完整交互。');}}>先体验构造演示 </button></div>:<><div className="snapshot-meta"><span className={`mode-badge ${snapshot.mode}`}>{snapshot.mode==='mock'?'构造数据演示':'真实接口快照'}</span><span>{snapshot.universe} · {snapshot.universeCount}只</span><span>{reportLabel(snapshot.report)}</span><span title={snapshot.id}>快照 {snapshot.id.slice(0,8)}</span></div><p className="subtle fetched-time">获取于 {time(snapshot.createdAt)}（北京时间）{needsFields?<strong> · 上次已确认结果（旧结果），当前策略尚未执行</strong>:changed?' · 条件修改后预览，待确认':''}{running?' · 获取中，以下为上次快照':''}</p>
    {evaluation.error?<div className="validation">{evaluation.error}</div>:validation.length?<div className="validation">条件有冲突或未澄清诉求，暂不生成结论。</div>:<>{needsFields&&<div className="validation">当前快照尚未获取：{missingFields.map(f=>registry[f].name).join('、')}。以下保留上次已确认结果；条件比较与独立影响已暂停。请重新获取并执行后生成新结论。</div>}<div className="summary-grid">{(['pass','fail','unknown'] as const).map(t=><button key={t} className={`${tab===t?'selected':''} ${t==='pass'?'pass-summary':''}`} onClick={()=>setTab(t)}><span>{{pass:'符合全部条件',fail:'至少一项未满足',unknown:'数据待核验'}[t]}</span><strong>{counts[t]}<small>只</small></strong><p>{{pass:'候选研究对象',fail:'查看排除依据',unknown:'缺失不当作0'}[t]}</p></button>)}</div>
    {comparison&&<div className="comparison"><div><strong>相对首次执行的条件变化</strong><span>同一快照 · {comparison.before} → {comparison.after}只符合</span></div><p>新增 <b>{comparison.added.length}</b> · 移出 <b>{comparison.removed.length}</b> · 保留 <b>{comparison.retained.length}</b>{comparison.pending.length>0&&<> · 转为待核验 <b>{comparison.pending.length}</b>（不计作移出）</>}</p>{comparison.added.length>0&&<small>新增：{comparison.added.join('、')}</small>}{comparison.removed.length>0&&<small>移出：{comparison.removed.join('、')}</small>}</div>}
    <div className="table-controls"><div className="tabs" aria-label="结果筛选">{(['pass','fail','unknown','all'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='all'?'全部':labels[t]} <span>{t==='all'?rows.length:counts[t]}</span></button>)}</div><div className="table-search"><Search size={14}/><input aria-label="搜索股票代码或名称" placeholder="代码 / 名称" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="table-scroll"><table><thead><tr><th>股票</th><th>状态</th>{[...new Set(resultStrategy.conditions.map(c=>c.field))].map(f=><th key={f}>{registry[f].name}</th>)}<th>证据</th></tr></thead><tbody>{visible.map(row=><tr key={row.code}><td><strong>{row.name}</strong><small>{row.code}</small></td><td><Pill status={row.status}/></td>{[...new Set(resultStrategy.conditions.map(c=>c.field))].map(f=><td className="metric-cell" key={f}><span>{formatValue(f,row.metrics[f]?.quality==='valid'?row.metrics[f]?.value??null:null)}</span>{row.metrics[f]?.quality!=='valid'&&<small>{({'missing':'缺失','invalid':'不适用','stale':'过期','error':'请求失败'} as Record<string,string>)[row.metrics[f]?.quality??'']??'未获取'}</small>}</td>)}<td><button className="evidence-button" aria-label={`查看${row.name}证据`} onClick={()=>setSelected(row.code)}>查看 </button></td></tr>)}</tbody></table>{visible.length===0&&<div className="table-empty">{search?'没有匹配的代码或名称。':tab==='pass'?'当前没有符合全部条件的股票。可查看未满足依据，再调整阈值。':'当前分类没有股票。'}</div>}</div><p className="table-footnote">总数核对：{counts.pass} + {counts.fail} + {counts.unknown} = {rows.length}。独立未满足数可能重叠，不可相加。</p></>}
    <details className="data-notes"><summary>数据口径与本版边界 ↓</summary><ul>{snapshot.warnings.map((s,i)=><li key={i}>{s}</li>)}<li>当前成分不等于历史成分；12只固定研究样本存在选择偏差。</li><li>AND中未满足优先；全部满足才入选；其余待核验。</li><li>不同指标窗口不合成为同一历史时点的可交易信号。</li></ul></details></>}
   </section></div><footer className="research-boundary"><ShieldCheck size={19}/><p><strong>研究辅助，保留判断。</strong> 提供条件筛选与事实解释，不提供买卖、仓位、收益承诺或自动交易。候选名单不代表适合个人投资；历史表现不能保证未来结果。</p><span>AI理解 → 人确认 → 工具执行 → 证据核验</span></footer>
  </main>
  {detail&&<div className="overlay" onClick={()=>setSelected(null)}><aside className="evidence-drawer" role="dialog" aria-modal="true" aria-label={`${detail.name}的筛选证据`} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null);}}><div className="drawer-header"><div><p className="eyebrow">EVIDENCE REVIEW</p><h2>{detail.name} <small>{detail.code}</small></h2></div><button autoFocus className="icon-button" onClick={()=>setSelected(null)} aria-label="关闭证据"><X size={22}/></button></div><Pill status={detail.status}/>{needsFields&&<p className="validation">上次已确认结果的证据，当前策略须重新取数。</p>}<p className="drawer-intro">{detail.status==='pass'?'每项条件均有有效数据且满足阈值。仅进入研究候选名单。':detail.status==='fail'?'至少一项有效数据未满足条件。其他缺失仍单独展示。':'没有已知未满足项，但至少一项缺少可验证数据。'}</p>{detail.checks.map(k=><article className="evidence-card" key={k.condition.id}><div><h3>{registry[k.condition.field].name}</h3><Pill status={k.status}/></div><p className="evidence-reason">{k.reason}</p><dl><dt>条件与口径</dt><dd>{formatCondition(k.condition)} · {registry[k.condition.field].period}</dd><dt>来源</dt><dd>{k.evidence?.source??'未获取'}</dd><dt>原始字段</dt><dd>{k.evidence?.rawField??'—'}</dd><dt>原始值</dt><dd>{Array.isArray(k.evidence?.rawValue)?`${k.evidence.rawValue.length}个价格点`:k.evidence?.rawValue===null||k.evidence?.rawValue===undefined?'null / 未返回':String(k.evidence.rawValue)}</dd><dt>标准化值</dt><dd>{k.evidence?.value==null?'—':`${k.evidence.value}（${registry[k.condition.field].percent?'内部小数':'倍'}） → ${formatValue(k.condition.field,k.evidence.value)}`}</dd><dt>上游元数据时间</dt><dd>{time(k.evidence?.observedAt)}</dd><dt>获取时间</dt><dd>{time(k.evidence?.fetchedAt)}</dd>{k.evidence?.reportPeriod&&<><dt>财报 / 公告日</dt><dd>{reportLabel(k.evidence.reportPeriod)} / {time(k.evidence.publishedAt)}</dd></>}<dt>请求标识</dt><dd>{k.evidence?.requestId??'未提供'}</dd><dt>接口路径</dt><dd>{k.evidence?.endpoint??'—'}</dd>{k.evidence?.calculation&&<><dt>计算公式</dt><dd>{k.evidence.calculation}</dd><dt>收益率样本数</dt><dd>{k.evidence.sampleCount??'不足'}</dd><dt>行情窗口</dt><dd>{time(k.evidence.windowStart)} 至 {time(k.evidence.windowEnd)}</dd></>}</dl>{k.evidence?.reason&&<p className="metric-hint">{k.evidence.reason}</p>}{Array.isArray(k.evidence?.rawValue)&&<details><summary>原始价格序列 ↓</summary><pre>{JSON.stringify(k.evidence.rawValue,null,2)}</pre></details>}</article>)}<p className="subtle">解释文字由确定性模板生成；AI不生成数值或筛选状态。</p></aside></div>}
  {showSaved&&<div className="overlay" onClick={()=>setShowSaved(false)}><section className="saved-dialog" role="dialog" aria-modal="true" aria-label="我的策略" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setShowSaved(false);}}><div className="section-title"><h2>我的策略</h2><button autoFocus className="icon-button" aria-label="关闭我的策略" onClick={()=>setShowSaved(false)}><X size={21}/></button></div><p className="subtle">保存在此浏览器，最多20份。重开后需核对并重新执行。</p>{saved.length===0?<div className="table-empty">还没有保存的策略。</div>:saved.map(s=><article className="saved-item" key={s.id}><div><h3>{s.strategy.name}</h3><p>{s.strategy.conditions.length}个条件 · {reportLabel(s.strategy.report)}</p><small>{time(s.savedAt)}</small></div><button className="quiet" disabled={running} onClick={()=>{const r=StrategySchema.safeParse(s.strategy);if(!r.success){setError('保存策略结构无法验证。');return;}if(mode==='mock'&&r.data.universe==='csi300')switchMode('real');update(r.data);setQuery(r.data.originalQuery);setSnapshot(null);setBaseline(null);setConfirmed(null);setShowSaved(false);setNotice('已重开策略；请核对可用报告期，确认后重新获取数据。');}}>重开 </button><button className="icon-button" aria-label={`删除保存策略${s.strategy.name}`} onClick={()=>removeSaved(s.id)}><Trash2 size={16}/></button></article>)}</section></div>}
 </div>;
}




